### ISSUE TITLE
著作権表記に関して

### ISSUE THREAD

**Issue by akiomik** [nulab/hubot-typetalk#12]
お世話になっております。鎌倉と申します。
以前hubot-typetalkを個人で開発し公開していたのですが、自分でメンテナンスできなくなったこともありnulabさんに引き取ってもらいました。
引き取ってもらえたことで私としても助かったのですが、久しぶりにリポジトリを確認して著作権表記に関して気になることがありました。

元となるhubot-typetalkはMITライセンスとして公開しており、`Copyright (c) 2013 Akiomi KAMAKURA`として`LICENSE`に記載していたのですが、現在は自分の著作権表記が`Copyright (c) 2014 Nulab Inc.`と書き換えられています。

自分の考えでは、

- 私が書いたコード -> 著作権はAkiomi KAMAKURAに帰属
- 譲渡後に書かれたコード -> 著作権はNulab Inc.に帰属

となるため、MITライセンス上は両者のライセンス表記が必要なのではないか、という認識です。

法律に関して全くの素人のため見当違いなことを申しているかもしれませんが、ご確認いただきたく思います。
よろしくお願いします。

**Comment by tsuyoshizawa** [comment]
@akiomik 鎌倉さん

まずライセンスに関して心配させてしまい申し訳ありません。

> MITライセンス上は両者のライセンス表記が必要なのではないか、という認識

鎌倉さんのほうで著作権放棄を行う等やりとりがないと思いますので、私個人として同じ認識です。
私も譲渡に関して知識がありませんため、一度私たちのほうで確認させてください。

**Comment by tsuyoshizawa** [comment]
念のため会社の法務にも確認してもらうようにしました。
来週の半ばぐらいには何かしら返事が行えるかと思います。

申し訳ありませんが、今しばらくお待ちいただければ、と思います。

**Comment by akiomik** [comment]
@tsuyoshizawa 迅速なご対応ありがとうございます！！

念のため、当時の担当者の方とのやりとり(twitterのDMとtypetalk上で行いました)を改めて確認しましたが、著作権放棄に関するやりとりは特に交わしておりませんでした。こちらのやりとりに関してはスクリーンショット等になってしまうと思いますが提出できると思いますので、必要な場合はご連絡いただければと思います。
引き続きよろしくお願いします。

**Comment by dragon3** [comment]
@akiomik さん、ご迷惑をおかけしてすみません。
確認したところ d074fd1537ac2c54fa3a0d7189d45cabeeddcb06 で自分が LICENSE を書き換えておりますね。
当時のことを覚えていないのですが、これは全くの自分のミスです。

@tsuyoshizawa より会社の法務に確認すると返信があってますが、自分としましては、あきらかにすぐ修正すべきと思いますので、 @tsuyoshizawa と話をし修正させていただくつもりです。

本当にすみませんでした。

**Comment by akiomik** [comment]
@dragon3 あまりお気になさらないでください。
自分としてもライセンスや譲渡に関して無頓着だったため、今の今まで気づかなかったわけですから。
私としては急いでいるわけではありませんので、法務の方から正式な判断が出てからのご対応でも問題はありませんが、当面の処置に関してはお任せいたします。

**Comment by dragon3** [comment]
@akiomik さん、#13 の Pull Request にて修正し、マージしました。
念の為、確認していただけると助かります。
よろしくお願いします。

**Comment by tsuyoshizawa** [comment]
意図せず変更してしまっていた、というところの確認が取れましたので、私としましても会社のほうに細かく確認してもらう必要はないと判断、またそのように報告しました。

**Comment by akiomik** [comment]
@tsuyoshizawa 承知しました。

@dragon3 確認いたしました。LGTMです 👍 

この度は数年前のことでお騒がせしましたが、迅速にご対応いただけて助かりました。
ありがとうございました。

**Comment by dragon3** [comment]
@akiomik 確認ありがとうございました。
そして、あらためて、本当にすみませんでした。
