### ISSUE TITLE
response error 発生時の再接続

### ISSUE THREAD

**Issue by nobuhito** [nulab/hubot-typetalk#4]
ネットワーク障害かなにかでエラーが発生するとそのままHubotが反応なしになってしまいます。

> [Wed Nov 04 2015 12:47:59 GMT+0900 (JST)] INFO Typetalk WebSocket connected
> [Wed Nov 04 2015 13:28:03 GMT+0900 (JST)] ERROR Typetalk response error: Error: connect ETIMEDOUT 54.244.122.179:443
> [Wed Nov 04 2015 13:28:03 GMT+0900 (JST)] ERROR Typetalk send error: Error: connect ETIMEDOUT 54.244.122.179:443
> [Wed Nov 04 2015 13:56:56 GMT+0900 (JST)] ERROR Typetalk response error: Error: read ECONNRESET
> [Wed Nov 04 2015 13:56:56 GMT+0900 (JST)] ERROR Typetalk send error: Error: read ECONNRESET

なにか対応方法はありますでしょうか？

**Comment by tksmd** [comment]
@nobuhito ご報告ありがとうございます :bow: 

ログからは WebSocket 側で切断を検知できていないように見受けられますね。( WebSocket で切断が検知できていたら再接続の処理が入るはずですので )

ネットワーク障害とのことですが、具体的にどのような状況であったか ( 例: WiFi が途中とぎれていた等 ) もし分かればお教えいただけますでしょうか？状況の再現の参考にさせていただきたく思います。

こちらは hubot-typetalk 側で対応するまでは、お手数ですがエラー見つけたときに hubot を再起動していただくのが確実かとは思われます。

**Comment by nobuhito** [comment]
もう少し調べてみたところ、エラーの発生と時間が経つと接続が切れてる件は別の原因のようでした。

Firewallの中からTypetalkへつないでいるのですが、時間が経つと接続が切れてしまうようです。その対応にパッチを作りましたので、よろしければ取り込んでいただければと思います。

ネットワークの障害エラーについてですが、こちらの環境でルーターの設定変更でおかしくなった時でした。その後はHubot-typetakでのエラーは発生していません。

**Comment by tsuyoshizawa** [comment]
こちら取り込みました。 CI の整備等、微修正したのち近日中に修正版をリリースします。
ありがとうございました。

**Comment by tsuyoshizawa** [comment]
@nobuhito こちらの機能を取り込んだ 0.2.0 をリリースしました。

**Comment by nobuhito** [comment]
さっそくアップデートかけて試してます。対応ありがとうございました。
